# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ethan K. Gordon
email: contact@ethankgordon.com
url: https://ethankgordon.com
tagline: PhD, Roboticist, Research Scientist
description: A Postdoctoral Researcher working on Dexterous Manipulation and Assistive Robotics

# Social settings
facebook_url: https://facebook.com/ekgekg
github_url: https://github.com/egordon
linkedin_url: https://www.linkedin.com/in/ekgordon
scholar_url: https://scholar.google.com/citations?user=hfmi3QwAAAAJ
twitter_url: https://twitter.com/EKGRobots

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: EKGRobots
  card: summary
logo: /images/robotic-arm.png
google_site_verification: alBrUFT9qPPAhLs69YkDiBtNtd640vl53IAbrqe9KYk
social:
  name: Ethan K. Gordon
  links:
    - https://github.com/egordon
    - https://facebook.com/ekgekg
    - https://twitter.com/EKGRobots
    - https://www.linkedin.com/in/ekgordon

plugins:
  - jekyll-seo-tag

collections:
  pubs:
    output: true
